import Head from "next/head";
import Category from "../components/Category";
import Pages from "../components/Pages";
import SearchNav from "../components/SearchNav";

export default function Home() {
  return (
    <div className="m-0 p-0 box-border font-Montserrat antialiased">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-[20%]">
        <SearchNav />
        <Category />
        <Pages />
      </div>
    </div>
  );
}
